-
  name: 'Psmb.Newsletter Subscriber Export'
  uriPattern: 'subscribers/export'
  defaults:
    '@package':    'Psmb.Newsletter'
    '@controller': 'Module\Newsletter\Subscriber'
    '@action':     'export'
  appendExceedingArguments: TRUE

-
  name: 'Psmb.Newsletter edit route'
  uriPattern: '{node}~newsletter/edit/{--newsletter.subscriber}'
  defaults:
    '@package':    'TYPO3.Neos'
    '@controller': 'Frontend\Node'
    '@format':     'html'
    '@action':     'show'
    '--newsletter':
      '@package': 'Psmb.Newsletter'
      '@controller': 'Subscription'
      '@action': 'edit'
      '@format': 'html'
  routeParts:
    node:
      handler: TYPO3\Neos\Routing\FrontendNodeRoutePartHandler
  appendExceedingArguments: TRUE

-
  name: 'Psmb.Newsletter unsubscribe route'
  uriPattern: '{node}~newsletter/unsubscribe/{--newsletter.subscriber}'
  defaults:
    '@package':    'TYPO3.Neos'
    '@controller': 'Frontend\Node'
    '@format':     'html'
    '@action':     'show'
    '--newsletter':
      '@package': 'Psmb.Newsletter'
      '@controller': 'Subscription'
      '@action': 'unsubscribe'
      '@format': 'html'
  routeParts:
    node:
      handler: TYPO3\Neos\Routing\FrontendNodeRoutePartHandler
  appendExceedingArguments: TRUE

-
  name: 'Psmb.Newsletter other routes'
  uriPattern: '{node}~newsletter/{--newsletter.@action}'
  defaults:
    '@package':    'TYPO3.Neos'
    '@controller': 'Frontend\Node'
    '@format':     'html'
    '@action':     'show'
    '--newsletter':
      '@package': 'Psmb.Newsletter'
      '@controller': 'Subscription'
      '@format': 'html'
  routeParts:
    node:
      handler: TYPO3\Neos\Routing\FrontendNodeRoutePartHandler
  appendExceedingArguments: TRUE

-
  name: 'Psmb.Newsletter AJAX routes'
  uriPattern: 'newsletter/{@action}'
  defaults:
    '@package':    'Psmb.Newsletter'
    '@controller': 'Newsletter'
    '@format':     'json'
    '@action':     'send'
  appendExceedingArguments: TRUE

-
  name: 'Psmb.Newsletter Tracking route'
  uriPattern: 'analytics/track'
  defaults:
    '@package':    'Psmb.Newsletter'
    '@controller': 'Analytics'
    '@action':     'track'
  appendExceedingArguments: TRUE

-
  name: 'Psmb.Newsletter Datasource Analytics'
  uriPattern: 'analytics/datasource'
  defaults:
    '@package':    'Psmb.Newsletter'
    '@controller': 'Module\Analytics'
    '@action':     'dataSource'
    '@format':     'json'
  appendExceedingArguments: TRUE
