
Flowpack:
  JobQueue:
    Common:
      queues:
        psmb-newsletter:
          className: Flowpack\JobQueue\Common\Queue\FakeQueue
        psmb-newsletter-web:
          className: Flowpack\JobQueue\Common\Queue\FakeQueue
          options:
            async: true
TYPO3:
  Flow:
    security:
      authentication:
        providers:
          'TYPO3.Neos:Backend':
            requestPatterns:
              'Psmb.Newsletter:Backend':
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'Psmb\Newsletter\Controller\.*'
    mvc:
      routes:
        'Psmb.Newsletter':
          position: 'before TYPO3.Neos'
  Neos:
    userInterface:
      translation:
        autoInclude:
          'Psmb.Newsletter': ['Main', 'Modules', 'NodeTypes/*']
      requireJsPathMapping:
        'Psmb.Newsletter/Views': 'resource://Psmb.Newsletter/Public/JavaScript/Inspector/Views'
    modules:
      management:
        submodules:
          subscribers:
            label: 'Psmb.Newsletter:Modules:newsletter.label'
            controller: \Psmb\Newsletter\Controller\Module\SubscriberController
            description: 'Psmb.Newsletter:Modules:newsletter.description'
            icon: icon-envelope
            actions:
              index:
                label: 'Manage newsletter subscribers'
                title: 'Manage newsletter subscribers'

Flowpack:
  JobQueue:
    Common:
      queues:
        'psmb-newsletter':
          className: 'Flowpack\JobQueue\Common\Queue\FakeQueue'
          options:
            async: true

Psmb:
  Newsletter:
    module:
      itemsPerPage: 18

#Psmb:
#  Newsletter:
#    globalSettings:
#      senderAddress: 'robot@server.com'
#      senderName: 'Your robot'
#    subscriptions:
#      -
#        identifier: 'daily'
#        renderer: 'Your:LetterRenderer'
#        label: 'Our daily newsletter'
#        interval: P1D
#        dimensions:
#          language: ['dimensionValues']
