TYPO3:
  Flow:
    security:
      authentication:
        providers:
          Typo3BackendProvider:
            requestPatterns:
              'Psmb.Newsletter:Backend':
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'Psmb\Newsletter\Controller\.*'
    mvc:
      routes:
        'Psmb.Newsletter':
          position: 'before TYPO3.Neos'
  Neos:
    userInterface:
      translation:
        autoInclude:
          'Psmb.Newsletter': ['Main', 'Modules', 'NodeTypes/*']
      requireJsPathMapping:
        'Psmb.Newsletter/Views': 'resource://Psmb.Newsletter/Public/JavaScript/Inspector/Views'
    typoScript:
      autoInclude:
        'Psmb.NewsLetter': TRUE
    modules:
      newsletter:
        label: 'Psmb.Newsletter:Modules:newsletter.label'
        controller: '\Psmb\Newsletter\Controller\Module\NewsletterController'
        description: 'Psmb.Newsletter:Modules:newsletter.description'
        icon: 'icon-envelope'
        submodules:
          subscribers:
            label: 'Psmb.Newsletter:Modules:newsletter.subscribers.label'
            controller: \Psmb\Newsletter\Controller\Module\Newsletter\SubscriberController
            description: 'Psmb.Newsletter:Modules:newsletter.subscribers.description'
            widgetTemplatePathAndFileName: 'resource://TYPO3.Neos/Private/Templates/Module/Widget.html'
            icon: icon-users
            actions:
              index:
                label: 'Manage newsletter subscribers'
                title: 'Manage newsletter subscribers'
          subscriptions:
            label: 'Psmb.Newsletter:Modules:newsletter.subscriptions.label'
            controller: \Psmb\Newsletter\Controller\Module\Newsletter\SubscriptionController
            description: 'Psmb.Newsletter:Modules:newsletter.subscriptions.description'
            widgetTemplatePathAndFileName: 'resource://TYPO3.Neos/Private/Templates/Module/Widget.html'
            icon: icon-paper-plane
            actions:
              index:
                label: 'Manage newsletter subscriptions'
                title: 'Manage newsletter subscriptions'
          analytics:
            label: 'Psmb.Newsletter:Modules:newsletter.analytics.label'
            controller: \Psmb\Newsletter\Controller\Module\Newsletter\AnalyticsController
            description: 'Psmb.Newsletter:Modules:newsletter.analytics.description'
            widgetTemplatePathAndFileName: 'resource://TYPO3.Neos/Private/Templates/Module/Widget.html'
            icon: icon-pie-chart
            actions:
              index:
                label: 'View newsletter analytics'
                title: 'View newsletter analytics'

Flowpack:
  JobQueue:
    Common:
      queues:
        psmb-newsletter-web:
          className: Flowpack\JobQueue\Common\Queue\FakeQueue
          options:
            async: true
        'psmb-newsletter':
          className: 'Flowpack\JobQueue\Common\Queue\FakeQueue'

Psmb:
  Newsletter:
    module:
      itemsPerPage: 25

#Psmb:
#  Newsletter:
#    globalSettings:
#      senderAddress: 'robot@server.com'
#      senderName: 'Your robot'
#    subscriptions:
#      -
#        identifier: 'daily'
#        renderer: 'Your:LetterRenderer'
#        label: 'Our daily newsletter'
#        interval: P1D
#        dimensions:
#          language: ['dimensionValues']
