
Flowpack:
  JobQueue:
    Common:
      queues:
        psmb-newsletter-web:
          className: Flowpack\JobQueue\Common\Queue\FakeQueue
          options:
            async: true
        psmb-newsletter:
          className: Flowpack\JobQueue\Common\Queue\FakeQueue
Psmb:
  Newsletter:
    module:
      itemsPerPage: 25
Neos:
  Flow:
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'Psmb.Newsletter:Backend':
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'Psmb\Newsletter\Controller\.*'
    mvc:
      routes:
        Psmb.Newsletter:
          position: 'before Neos.Neos'
  Neos:
    userInterface:
      translation:
        autoInclude:
          Psmb.Newsletter:
            - Main
            - Modules
            - 'NodeTypes/*'
      requireJsPathMapping:
        Psmb.Newsletter/Views: 'resource://Psmb.Newsletter/Public/JavaScript/Inspector/Views'
    modules:
      newsletter:
        label: 'Psmb.Newsletter:Modules:newsletter.label'
        controller: \Psmb\Newsletter\Controller\Module\NewsletterController
        description: 'Psmb.Newsletter:Modules:newsletter.description'
        icon: icon-envelope
        submodules:
          subscribers:
            label: 'Psmb.Newsletter:Modules:newsletter.subscribers.label'
            controller: \Psmb\Newsletter\Controller\Module\Newsletter\SubscriberController
            description: 'Psmb.Newsletter:Modules:newsletter.subscribers.description'
            widgetTemplatePathAndFileName: 'resource://Neos.Neos/Private/Templates/Module/Widget.html'
            icon: icon-users
            actions:
              index:
                label: 'Psmb.Newsletter:Modules:newsletter.subscribers.button'
                title: 'Manage newsletter subscribers'
          subscriptions:
            label: 'Psmb.Newsletter:Modules:newsletter.subscriptions.label'
            controller: \Psmb\Newsletter\Controller\Module\Newsletter\SubscriptionController
            description: 'Psmb.Newsletter:Modules:newsletter.subscriptions.description'
            widgetTemplatePathAndFileName: 'resource://Neos.Neos/Private/Templates/Module/Widget.html'
            icon: icon-paper-plane
            actions:
              index:
                label: 'Psmb.Newsletter:Modules:newsletter.subscriptions.button'
                title: 'Manage newsletter subscriptions'
          analytics:
            label: 'Psmb.Newsletter:Modules:newsletter.analytics.label'
            controller: \Psmb\Newsletter\Controller\Module\Newsletter\AnalyticsController
            description: 'Psmb.Newsletter:Modules:newsletter.analytics.description'
            widgetTemplatePathAndFileName: 'resource://Neos.Neos/Private/Templates/Module/Widget.html'
            icon: icon-pie-chart
            actions:
              index:
                label: 'Psmb.Newsletter:Modules:newsletter.analytics.button'
                title: 'View newsletter analytics'
    fusion:
      autoInclude:
        Psmb.NewsLetter: true
